### ISSUE TITLE
Linux release / compile instructions

### ISSUE THREAD

**Issue by fulcus** [stignarnia/Webex-Launcher-Auto#5]
Sarebbe utile supportare anche linux/macos o includere istruzioni per compilare il programma per la propria piattaforma

**Comment by stignarnia** [comment]
Ci ho provato e non ci sono riuscito. Siccome il programma è fatto con Windows Forms e .NET Framework 4.8 funziona solo su Windows. .NET 6 è fantastico come compatibilità sia di sistemi operativi che di architetture però hanno smesso di supportare WinForms. A quanto ho capito bisognerà usare .NET MAUI per le app grafiche ma non sono ancora riuscito a capire come, anche perché è in alpha. Se hai altre idee che non includano riscrivere tutto con GTK scrivi pure.

**Comment by stignarnia** [comment]
Webex nuovo, quello non meetings, supporta di default la cronologia delle chiamate
